groups:
- name: instance_alerts
  rules:
  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High CPU Usage on instance {{ $labels.instance }}"
      description: "CPU usage is above 80% (current value: {{ $value }}%)"

  - alert: HighMemoryUsage
    expr: 100 * (1 - (sum by(instance) (node_memory_MemAvailable_bytes) / sum by(instance) (node_memory_MemTotal_bytes))) > 80
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High Memory Usage on instance {{ $labels.instance }}"
      description: "Memory usage is above 80% (current value: {{ $value }}%)"

  - alert: HighDiskUsage
    expr: 100 * (1 - (node_filesystem_avail_bytes{fstype=~"ext4|xfs"} / node_filesystem_size_bytes{fstype=~"ext4|xfs"})) > 80
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High Disk Usage on instance {{ $labels.instance }} for filesystem {{ $labels.mountpoint }}"
      description: "Disk usage is above 80% on {{ $labels.instance }} (current value: {{ $value }}%) for filesystem {{ $labels.mountpoint }}"
