{
 "title": "NOC Dashboard",
 "tags": [
  "Prometheus",
  "All unix servers"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "label": "IP", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "IP",
    "query": {
     "query": "label_values({job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Online Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"$job\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"$job\"} == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "label_join(node_uname_info{job=~\"$job\", instance=~\"$instance\"}, \"status\", \"\", \"up\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{instance=~\"$instance\",job=~\"$job\"})by(instance)"
    },
    {
     "expr": "sum by (instance) (node_memory_MemTotal_bytes{instance=~\"$instance\", job=~\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\",mode='system'}) by (instance)"
    },
    {
     "expr": "100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance\", job=~\"$job\"}[5m])))",
     "legendFormat": "{{CPU}}"
    },
    {
     "expr": "100 * (1 - (sum by (instance) (node_memory_MemAvailable_bytes{instance=~\"$instance\", job=~\"$job\"}) / sum by (instance) (node_memory_MemTotal_bytes{instance=~\"$instance\", job=~\"$job\"})))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{instance=~\"$instance\",job=~\"$job\"}[5m])) by (instance)"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{instance=~\"$instance\",job=~\"$job\"}[5m])) by (instance)"
    },
    {
     "expr": "100 * (node_filesystem_size_bytes{instance=~\"$instance\", job=~\"$job\", mountpoint=\"/\"} - node_filesystem_free_bytes{instance=~\"$instance\", job=~\"$job\", mountpoint=\"/\"}) / node_filesystem_size_bytes{instance=~\"$instance\", job=~\"$job\", mountpoint=\"/\"}\r\n"
    },
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"$instance\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$instance\",job=~\"$job\"}) / (node_memory_SwapTotal_bytes{instance=~\"$instance\",job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((sum by(instance) (irate(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\", mode!=\"idle\"}[5m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}[5m])))) * 100) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TOP 5 Hosts CPU usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 11 },
   "targets": [
    {
     "expr": "topk(5, 100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance\", job=~\"$job\"}[5m])))) * on(instance) group_left(nodename) node_uname_info\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 - ((node_memory_MemAvailable_bytes{job=\"$job\",instance=~\"$instance\"} * 100) / node_memory_MemTotal_bytes{job=~\"$job\",instance=~\"$instance\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TOP 5 Hosts Memory usage",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 13, "y": 19 },
   "targets": [
    {
     "expr": "(100 - ((node_memory_MemAvailable_bytes{job=\"$job\", instance=~\"$instance\"} * 100) / node_memory_MemTotal_bytes{job=~\"$job\", instance=~\"$instance\"}))\r\n* on(instance) group_left(nodename) node_uname_info\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage in Percentage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_filesystem_avail_bytes{job=\"$job\",instance=~\"$instance\"} / node_filesystem_size_bytes{job=\"$job\",instance=~\"$instance\"})) >= 1\r\n",
     "legendFormat": "{{mountpoint}} -{{instance}}"
    }
   ]
  }
 ]
}